CREATE TYPE genre AS ENUM (
    'ACTION', 'ADVENTURE', 'COMEDY', 'DRAMA', 'FANTASY', 'HORROR', 'SCIENCE_FICTION',
    'THRILLER', 'ROMANCE', 'DOCUMENTARY', 'ANIMATION', 'MUSICAL', 'WESTERN', 'WAR',
    'HISTORICAL', 'CRIME', 'BIOGRAPHY', 'FAMILY'
);